"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/src/lib/api";

export default function LoginPage(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setLoading(true);try{const d=await apiRequest("/auth/login",{method:"POST",body:JSON.stringify({email,password})});const token=d?.token||d?.access_token;if(!token)throw new Error("Сервер не вернул токен");localStorage.setItem("token",token);router.replace(d?.user?.role === "business" ? "/business/tasks" : "/profile");}catch(e:any){setError(e?.message||"Не удалось войти")}finally{setLoading(false)}}
 return <main className="ep-auth"><div className="ep-auth-grid"><section className="ep-auth-intro"><Link href="/" className="ep-brand"><img src="/site-logo.png" alt="Старт Комьюнити" className="ep-platform-logo" /></Link><div><div className="ep-eyebrow">ВОЗВРАЩАЙТЕСЬ К РАБОТЕ</div><h1>Продолжайте<br/><span>создавать опыт.</span></h1><p>Решайте реальные задачи, развивайте стек и собирайте портфолио, которое можно показать работодателю.</p></div><Link href="/" className="ep-back">← На главную</Link></section><section className="ep-auth-panel"><div className="ep-auth-card"><div className="ep-eyebrow">АККАУНТ</div><h2>Вход</h2><p className="ep-auth-muted">Введите данные, чтобы продолжить.</p><form onSubmit={submit} className="ep-form"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label>Пароль<div className="ep-password-field"><input type={showPassword ? "text" : "password"} value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••"/><button type="button" className="ep-password-toggle" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword ? "Скрыть пароль" : "Показать пароль"} title={showPassword ? "Скрыть пароль" : "Показать пароль"}>{showPassword ? <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z" stroke="currentColor" strokeWidth="1.7"/><circle cx="12" cy="12" r="2.6" stroke="currentColor" strokeWidth="1.7"/></svg> : <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M3 3l18 18" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/><path d="M10.6 6.2A10.5 10.5 0 0 1 12 6c6.5 0 10 6 10 6a18.6 18.6 0 0 1-3.1 3.7M6.1 6.9C3.2 8.7 2 12 2 12a18.4 18.4 0 0 0 6.4 4.8A10.4 10.4 0 0 0 12 18c1.1 0 2.1-.2 3-.5" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg> }</button></div></label>{error&&<div className="ep-error">{error}</div>}<button className="ep-button" disabled={loading}>{loading?"Входим…":"Войти →"}</button></form><p className="ep-auth-bottom">Нет аккаунта? <Link href="/register">Зарегистрироваться</Link></p></div></section></div></main>
}
